arcoiris=("azul","verde","rojo","amarillo")
print(arcoiris)
print("-longitud arcoiris--")
print(len(arcoiris))
animales=("pantera",20,"estatura",1.7)
print(animales)
print("elementos de la tuplas")
print(animales[2])
rateros=("juan","ana","pedro")
f=list(rateros)
f[1]="polainas"
e=tuple(f)
print(e)
print("agrgando elementos")
Nanimal=("body","chetos")
f=list(Nanimal)
print(f)
f.append("tontolin")
otratupla=tuple(f)
print(otratupla)
print("uso de for en tuplas")
for colores in arcoiris:
    print(colores)

